reading the dataset

In [ ]:
import pandas as pd
cars = pd.read_csv('/content/car data.csv')

cars.head (10)

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,0
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,0
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,0
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,0

data analysis

In [ ]:
cars.info()
cars.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Selling_type   301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Driven_kms       0
Fuel_Type        0
Selling_type     0
Transmission     0
Owner            0
dtype: int64

Preprocessing the year coulmn so it become more usful

In [ ]:
cars['Car_Age'] = 2024 - cars['Year']
cars

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner,Car_Age
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,10
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,11
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,7
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,13
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,10
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0,8
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0,9
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0,15
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0,7
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0,8

transform categorical data into numerical data

In [ ]:
from sklearn.preprocessing import LabelEncoder


encoder = LabelEncoder()

cars['Fuel_Type'] = encoder.fit_transform(cars['Fuel_Type'])
cars['Selling_type'] = encoder.fit_transform(cars['Selling_type'])
cars['Transmission'] = encoder.fit_transform(cars['Transmission'])
cars['Car_Name'] = encoder.fit_transform(cars['Car_Name'])

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner,Car_Age
0,90,2014,3.35,5.59,27000,2,0,1,0,10
1,93,2013,4.75,9.54,43000,1,0,1,0,11
2,68,2017,7.25,9.85,6900,2,0,1,0,7
3,96,2011,2.85,4.15,5200,2,0,1,0,13
4,92,2014,4.60,6.87,42450,1,0,1,0,10
...,...,...,...,...,...,...,...,...,...,...
296,69,2016,9.50,11.60,33988,1,0,1,0,8
297,66,2015,4.00,5.90,60000,2,0,1,0,9
298,69,2009,3.35,11.00,87934,2,0,1,0,15
299,69,2017,11.50,12.50,9000,1,0,1,0,7
300,66,2016,5.30,5.90,5464,2,0,1,0,8

libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

Split Data into Training and Testing

In [ ]:
X = cars[['Car_Age', 'Present_Price', 'Fuel_Type', 'Selling_type', 'Transmission','Car_Name','Driven_kms','Owner']]
y = cars['Selling_Price']

X_train, X_test, y_train, y_test = train_test_split(X, y)

the model

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R2 Score: {r2}')

Mean Squared Error: 2.8706744556034267
R2 Score: 0.8531140367905327